version: '3'
services:
  selenoid:
    image: "aerokube/selenoid"
    network_mode: bridge
    ports:
      - "4444:4444"
    volumes:
      - "./:/etc/selenoid/"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/path/to/config/video:/opt/selenoid/video"
      - "/path/to/config/logs:/opt/selenoid/logs"
  selenoid-ui:
    image: "aerokube/selenoid-ui"
    network_mode: bridge
    links:
     - selenoid
    ports:
     - "8080:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]