name: Java CI with Maven and Email Notification

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - '*'
    tags:
      - '*'
    paths:
      - '**'
      - '!*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          dockerfile: Dockerfile

      - name: Build and run Docker container
        run: |
          docker build -t maven-selenium .
          docker run --rm maven-selenium

      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Create allure-results directory
        if: always()
        run: mkdir -p target/allure-results

      - name: Allure set up
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: target/allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history

      - name: Compile allure Reports
        if: always()
        run: mvn allure:report

      - name: Package Allure reports into zip file
        if: always()
        run: zip -r allure-reports.zip target/site/allure-maven-plugin

      - name: Send mail
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          connection_url: smtp://${{ secrets.logpass }}@smtp-zen.alwaysdata.net:587
          subject: GitHub Actions Job Result
          to: today_na@tutanota.com
          from: Luke Skywalker <zen@alwaysdata.net>
          ignore_cert: true
          attachments: allure-reports.zip
          body: |
            Build job of ${{ github.repository }} completed successfully!

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
