name: Java CI with Maven and Email Notification

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
    paths:
      - '**'
      - '!*.md'

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          connection_url: smtp://today_na@zenwarrior228.ru:dLP9SDO4rj1k@connect.smtp.bz:587
          subject: GitHub Actions Job Result
          to: today_na@mail.ru
          from: Luke Skywalker <today_na@zenwarrior228.ru>
          body: |
            Build job of ${{ github.repository }} completed successfully!