
name: Java CI with Maven

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
    paths:
      - '**'
      - '!*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'
          cache: maven

      - name: Install Chrome browser
        run: |
          CHROME_VERSION="114.0.5735.90"
          wget -q -O /tmp/chrome.deb https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_${CHROME_VERSION}-1_amd64.deb
          sudo dpkg -i /tmp/chrome.deb
          sudo apt-get install -f

      - name: Run UI Way2 and Practice1, Practice2 tests
        run: mvn -B package --file pom.xml

      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Create allure-results directory
        run: mkdir -p target/allure-results

      - name: Allure set up
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: target/allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history

      - name: Set permissions for Allure
        run: sudo chmod -R 777 target/allure-results

      - name: Compile allure Reports
        run: mvn allure:report

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history

      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          # Specify connection via URL (replaces server_address, server_port, secure,
          # username and password)
          #
          # Format:
          #
          #  * smtp://user:password@server:port
          #  * smtp+starttls://user:password@server:port
          connection_url: smtp://today_na@mail.ru:dLP9SDO4rj1k@connect.smtp.bz:2525
          # Required mail server address if not connection_url:
          server_address: connect.smtp.bz
          # Server port, default 25:
          server_port: 2525
          # Optional whether this connection use TLS (default is true if server_port is 465)
          secure: true
          # Optional (recommended) mail server username:
          username: today_na@mail.ru
          # Optional (recommended) mail server password:
          password: dLP9SDO4rj1k
          # Required mail subject:
          subject: Github Actions job result
          # Required recipients' addresses:
          to: today_na@mail.ru
          # Required sender full name (address can be skipped):
          from: Luke Skywalker # <user@example.com>
          # Optional plain body:
          body: Build job of ${{github.repository}} completed successfully!
          # Optional HTML body read from file:
          html_body: file://README.html
          # Optional carbon copy recipients:
          cc: kyloren@example.com,leia@example.com
          # Optional blind carbon copy recipients:
          bcc: r2d2@example.com,hansolo@example.com
          # Optional recipient of the email response:
          reply_to: luke@example.com
          # Optional Message ID this message is replying to:
          in_reply_to: <random-luke@example.com>
          # Optional unsigned/invalid certificates allowance:
          ignore_cert: true
          # Optional converting Markdown to HTML (set content_type to text/html too):
          convert_markdown: true
          # Optional attachments:
          attachments: attachments.zip,git.diff,./dist/static/*.js
          # Optional priority: 'high', 'normal' (default) or 'low'
          priority: low
          # Optional nodemailerlog: true/false
          nodemailerlog: false
          # Optional nodemailerdebug: true/false if true lognodem will also be set true
          nodemailerdebug: false